In [2]:
import numpy as np

In [2]:
j1 = np.array([1,1,1,1,1,1])

In [8]:
j2 = np.array([-1.1499504413306605, -2.5276477635487886, -0.7877716080698223, -0.3372901507005057, -3.755025135160846, -4.757863235315354])

In [9]:
np.all(np.less(np.abs(j2),np.array([3.14,3.14,3.14,3.14,3.14,3.14])))

False

In [13]:
np.pi/2

1.5707963267948966

In [18]:
np.full(6,[np.pi/2])

array([1.57079633, 1.57079633, 1.57079633, 1.57079633, 1.57079633,
       1.57079633])

### Shape

In [13]:
data = np.arange(36, dtype='float32')
data.resize((3,4,3))

In [14]:
data.shape

(3, 4, 3)

### MEMMAP

In [8]:
from tempfile import mkdtemp
import os.path as path
import numpy as np
filename = path.join(mkdtemp(), 'temp.dat')

In [9]:
#writing
data = np.arange(12, dtype='float32')
data.resize((3,4))
fp = np.memmap(filename, dtype='float32', mode='w+', shape=(3,4))
fp[:] = data[:]
fp.flush()

In [11]:
#reading
newfp = np.memmap(filename, dtype='float32', mode='r', shape=(3,4))
np.array(newfp)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [97]:
tr = np.array([ [ 0.0, 0.0, 1.0, 0.0,], 
               [ 0.0, -1.0, 0.0, 0.06772,], 
               [ 1.0, 0.0, 0.0, 0.744,], 
               [ 0.0, 0.0, 0.0, 1.0,],])

In [98]:
from scipy.spatial.transform import Rotation as R
rot = R.from_euler('z', -45, degrees=True)

In [99]:
rot.as_matrix()

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678, -0.        ],
       [-0.        ,  0.        ,  1.        ]])

In [100]:
a = np.eye(4)
a[:3,:3]=rot.as_matrix()
print(a)

[[ 0.70710678  0.70710678  0.          0.        ]
 [-0.70710678  0.70710678 -0.          0.        ]
 [-0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [101]:
a@tr

array([[ 0.        , -0.70710678,  0.70710678,  0.04788527],
       [ 0.        , -0.70710678, -0.70710678,  0.04788527],
       [ 1.        ,  0.        ,  0.        ,  0.744     ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [102]:
tr_final = tr[:3,:3]@rot.as_matrix()[:3,:3]

In [103]:
tr_final

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ]])

In [104]:
r1 = R.from_matrix(tr_final)

In [105]:
r1.as_rotvec()

array([1.7599884 , 0.72901107, 1.7599884 ])

In [5]:
np.degrees(np.array([-1.04378206, -1.97310938, -1.43369782, -2.82966294, -2.6047774 ,
       -2.26138717]))

array([ -59.80430677, -113.05083999,  -82.14483418, -162.12774391,
       -149.24275159, -129.56794069])