In [11]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [43]:
tr = np.array([[0, 0, 1, 0],
               [0, -1, 0, 0.06772],
               [1, 0, 0, 0.744],
               [0, 0, 0, 1]]) 

In [51]:
rot = R.from_euler('z', -45, degrees=True)
tr_offset = np.eye(4)
tr_offset[:3,:3] = rot.as_matrix()
tr_offset

array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [-0.70710678,  0.70710678, -0.        ,  0.        ],
       [-0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [52]:
tr_eef = tr_offset @ tr
print(tr_eef)

[[ 0.         -0.70710678  0.70710678  0.04788527]
 [ 0.         -0.70710678 -0.70710678  0.04788527]
 [ 1.          0.          0.          0.744     ]
 [ 0.          0.          0.          1.        ]]


In [53]:
R.from_matrix(tr_eef[:3,:3]).as_rotvec()

array([ 1.7599884 , -0.72901107,  1.7599884 ])

In [54]:
tr_eef

array([[ 0.        , -0.70710678,  0.70710678,  0.04788527],
       [ 0.        , -0.70710678, -0.70710678,  0.04788527],
       [ 1.        ,  0.        ,  0.        ,  0.744     ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [56]:
r.from_matrix(tr_eef)

ValueError: Expected `matrix` to have shape (3, 3) or (N, 3, 3), got (4, 4)